spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${BANK_LOCAL_DB_NAME}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${BANK_LOCAL_DB_USERNAME}
    password: ${BANK_LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true