spring:
  datasource:
    url: jdbc:mysql://${BANK_DB_IP}:${BANK_DB_PORT}/${BANK_DB_NAME}?useUnicode=true&serverTimezone=Asia/Seoul
    username: ${BANK_DB_USERNAME}
    password: ${BANK_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false